// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LM4CVrfJqGgVXUMnEDPHj58uwfW7TZ4',
    appId: '1:315645134975:web:7eb133dff064935c8e974a',
    messagingSenderId: '315645134975',
    projectId: 'mynotes-aadithya',
    authDomain: 'mynotes-aadithya.firebaseapp.com',
    storageBucket: 'mynotes-aadithya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKoDcUObykVLBBYozYZcK87n6CSh9uE4',
    appId: '1:315645134975:android:585c3bd772e1c7978e974a',
    messagingSenderId: '315645134975',
    projectId: 'mynotes-aadithya',
    storageBucket: 'mynotes-aadithya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYXfvwet0Dal1tORjgUIMPg1CLjmR3Z0',
    appId: '1:315645134975:ios:b92811af48778af68e974a',
    messagingSenderId: '315645134975',
    projectId: 'mynotes-aadithya',
    storageBucket: 'mynotes-aadithya.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYXfvwet0Dal1tORjgUIMPg1CLjmR3Z0',
    appId: '1:315645134975:ios:b92811af48778af68e974a',
    messagingSenderId: '315645134975',
    projectId: 'mynotes-aadithya',
    storageBucket: 'mynotes-aadithya.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6LM4CVrfJqGgVXUMnEDPHj58uwfW7TZ4',
    appId: '1:315645134975:web:af0d2642308bb4078e974a',
    messagingSenderId: '315645134975',
    projectId: 'mynotes-aadithya',
    authDomain: 'mynotes-aadithya.firebaseapp.com',
    storageBucket: 'mynotes-aadithya.firebasestorage.app',
  );
}
